"""Input validation facade.

Focused validation_* modules own text, registration, site settings, profile,
content, pagination, and trust-limit helpers. This module preserves existing imports.
"""

from __future__ import annotations

from .validation_content import (
    clean_id_list,
    clean_poll_payload,
    clean_post_content,
    clean_reaction_emoji,
    clean_report_category,
    clean_report_priority,
    clean_report_status,
    clean_sort_order,
    clean_thread_prefix,
    clean_thread_state_mode,
    clean_thread_template,
    normalize_tags,
    normalize_thread_prefixes,
)
from .validation_limits import count_links, user_account_age_days
from .validation_pagination import parse_pagination_query, parse_pagination_value, resolve_pagination
from .validation_profile import (
    clean_discord_username,
    clean_dm_privacy,
    clean_email,
    clean_profile_accent,
    clean_profile_badge,
    clean_role_name,
    clean_signature,
    clean_status_text,
)
from .validation_registration import (
    blocked_username_patterns,
    clean_invite_code,
    clean_password,
    clean_username,
    ensure_username_allowed_for_registration,
    find_valid_invite_code,
    generate_invite_code,
    get_registration_settings,
    is_approved_user,
    list_invite_codes,
    list_pending_registrations,
    pending_registration_count,
    registration_controls_payload,
    registration_status,
    serialize_invite_code,
    serialize_pending_registration,
    serialize_registration_settings,
    username_matches_blocked_pattern,
)
from .validation_site import (
    clean_optional_url,
    clean_site_theme,
    get_site_settings,
    normalize_feature_toggles,
    normalize_footer_links,
    serialize_site_settings,
    site_setting_value,
)
from .validation_text import clean_slug, clean_text, slugify_text

__all__ = [
    "blocked_username_patterns",
    "clean_discord_username",
    "clean_dm_privacy",
    "clean_email",
    "clean_id_list",
    "clean_invite_code",
    "clean_optional_url",
    "clean_password",
    "clean_poll_payload",
    "clean_post_content",
    "clean_profile_accent",
    "clean_profile_badge",
    "clean_reaction_emoji",
    "clean_report_category",
    "clean_report_priority",
    "clean_report_status",
    "clean_role_name",
    "clean_signature",
    "clean_site_theme",
    "clean_slug",
    "clean_sort_order",
    "clean_status_text",
    "clean_text",
    "clean_thread_prefix",
    "clean_thread_state_mode",
    "clean_thread_template",
    "clean_username",
    "count_links",
    "ensure_username_allowed_for_registration",
    "find_valid_invite_code",
    "generate_invite_code",
    "get_registration_settings",
    "get_site_settings",
    "is_approved_user",
    "list_invite_codes",
    "list_pending_registrations",
    "normalize_feature_toggles",
    "normalize_footer_links",
    "normalize_tags",
    "normalize_thread_prefixes",
    "parse_pagination_query",
    "parse_pagination_value",
    "pending_registration_count",
    "registration_controls_payload",
    "registration_status",
    "resolve_pagination",
    "serialize_invite_code",
    "serialize_pending_registration",
    "serialize_registration_settings",
    "serialize_site_settings",
    "site_setting_value",
    "slugify_text",
    "user_account_age_days",
    "username_matches_blocked_pattern",
]
